In [2]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 그래프 기본 테마 설정
# https://coldbrown.co.kr/2023/07/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%8B%A4%EC%A0%84%ED%8E%B8-08-seaborn-sns-set%EC%9D%84-%ED%86%B5%ED%95%B4-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 복잡한 통계 처리를 위한 라이브러리
from scipy import stats

# 필요한 패키지
import os

In [3]:
# 현재 경로 확인
os.getcwd()

'c:\\Users\\admin\\Desktop\\mid_project\\MidProject\\ipynbTest\\Junhyeok'

In [4]:

# 상위 폴더로 이동
os.chdir('../../')

### 전처리

In [5]:
registerd_df = pd.read_csv("data/processed/등록외국인_현황_국적별_구별_2023년3분기.csv", index_col=0)
registerd_df.head()

,국적,성별,소계,종로구,중구,용산구,성동구,광진구,동대문구,중랑구,...,강서구,구로구,금천구,영등포구,동작구,관악구,서초구,강남구,송파구,강동구
0,소계,남자,107958,4597,4873,7842,2966,6167,6468,2030,...,2470,12207,7094,11682,4342,6190,2087,2452,2568,1812
1,소계,여자,140420,6585,5547,6698,4211,9188,11407,3113,...,3169,10679,6371,11022,6244,9220,2275,2882,3203,2256
2,한국계 중국인,남자,37916,415,537,295,599,1723,797,522,...,860,9318,5371,8415,1529,2888,180,156,978,688
3,한국계 중국인,여자,31756,434,529,343,605,1714,797,599,...,859,6386,3872,6600,1426,2679,225,263,966,652
4,중국,남자,21288,1095,1251,200,909,1736,2313,237,...,329,2061,1045,1989,1185,914,295,467,357,188

In [6]:

# 국적 + 성별 결합
registerd_df['국적_성별'] = registerd_df['국적'].astype(str).str.strip() + "(" + registerd_df['성별'].astype(str).str.strip() + ")"

# 지역 컬럼만 추출
region_columns = registerd_df.columns.difference(['국적', '성별', '소계', '국적_성별']).tolist()

# 필요한 컬럼만 남기고 transpose
region_df = registerd_df[['국적_성별'] + region_columns].copy()
region_df = region_df.set_index('국적_성별').T

# 튜플 형태 컬럼 이름 제거
region_df.columns = [col[0] if isinstance(col, tuple) else col for col in region_df.columns]

# 숫자 변환
region_df = region_df.apply(pd.to_numeric, errors='coerce')

#  확인
region_df.head()

,소계(남자),소계(여자),한국계 중국인(남자),한국계 중국인(여자),중국(남자),중국(여자),미국(남자),미국(여자),타이완(남자),타이완(여자),...,페 루(남자),페 루(여자),덴 마 크(남자),덴 마 크(여자),모 로 코(남자),모 로 코(여자),이 라 크(남자),이 라 크(여자),기 타(남자),기 타(여자)
강남구,2452,2882,156,263,467,466,467,446,63,85,...,1.0,2.0,5.0,3.0,3.0,11.0,NaN,NaN,75,97
강동구,1812,2256,688,652,188,422,79,130,26,51,...,2.0,1.0,NaN,NaN,3.0,4.0,NaN,NaN,17,22
강북구,1613,3036,360,398,264,738,51,46,51,76,...,NaN,1.0,NaN,NaN,1.0,5.0,NaN,NaN,24,54
강서구,2470,3169,860,859,329,683,89,112,119,150,...,NaN,1.0,1.0,2.0,4.0,10.0,NaN,1.0,48,41
관악구,6190,9220,2888,2679,914,1831,143,231,54,140,...,3.0,15.0,7.0,4.0,15.0,47.0,NaN,2.0,193,285

In [7]:
region_df.isna().sum()
region_df = region_df.fillna(0)

In [8]:
print(region_df.isna().sum().sum())

0

In [9]:
region_df.to_csv("data/processed/등록외국인_현황_국적별_구별_2023_3분기.csv", index=True, encoding='utf-8-sig')

### 확인용

In [10]:
fly_df = pd.read_csv('data/processed/청소년비행데이터_2023.csv')

In [11]:
fly_df

,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
0,202301,서울강동,24,9,10,5,0,0,2,22,...,0,0,1,1,2,0,3,4,3,3
1,202301,서울송파,45,36,6,3,0,0,5,40,...,1,1,0,3,4,2,5,4,7,6
2,202301,서울서초,23,12,3,8,0,0,1,22,...,0,0,0,0,2,4,4,4,2,5
3,202301,서울강북,52,18,18,16,0,0,6,45,...,0,3,3,0,2,4,4,3,5,4
4,202301,서울광진,35,15,9,11,0,0,2,32,...,2,0,0,3,3,5,2,2,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,202312,서울남대문,6,5,0,1,0,0,0,6,...,0,0,0,3,0,2,1,0,0,0
381,202312,서울마포,102,45,24,33,0,0,4,95,...,1,7,5,11,16,8,9,17,13,2
382,202312,서울종로,3,2,1,0,0,0,0,2,...,0,0,0,0,0,0,1,1,1,0
383,202312,서울용산,2,0,1,1,0,0,1,1,...,0,0,0,0,1,0,0,0,1,0
384,202312,ETC,462,268,104,90,0,0,25,389,...,19,29,39,33,29,30,51,46,59,43

In [12]:
# 접수년월 컬럼을 삭제
fly_df.drop('접수년월', axis=1, inplace=True)
fly_df.head()

,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,접수긴급유형민원,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
0,서울강동,24,9,10,5,0,0,2,22,0,...,0,0,1,1,2,0,3,4,3,3
1,서울송파,45,36,6,3,0,0,5,40,0,...,1,1,0,3,4,2,5,4,7,6
2,서울서초,23,12,3,8,0,0,1,22,0,...,0,0,0,0,2,4,4,4,2,5
3,서울강북,52,18,18,16,0,0,6,45,1,...,0,3,3,0,2,4,4,3,5,4
4,서울광진,35,15,9,11,0,0,2,32,1,...,2,0,0,3,3,5,2,2,4,4

In [13]:
# 경찰서명이 담길 리스트를 만들어준다. 
police_name = []

for name in fly_df['경찰서명']:
    police_name.append(name)

In [14]:
print('\n'.join(police_name))

서울강동
서울송파
서울서초
서울강북
서울광진
서울중랑
서울종암
서울영등포
서울서부
서울동대문
서울금천
서울중부
서울마포
서울강남
서울은평
서울수서
서울강서
서울노원
서울성동
서울도봉
서울성북
서울청
서울혜화
서울방배
서울관악
서울용산
서울서대문
서울양천
서울동작
서울구로
ETC
서울강북
서울영등포
서울광진
서울도봉
서울송파
서울강동
서울서대문
서울강남
서울동대문
서울성동
서울노원
서울은평
서울서부
서울마포
서울금천
서울중랑
서울중부
서울종암
서울수서
서울종로
서울서초
서울강서
서울동작
서울관악
서울남대문
서울성북
서울구로
서울양천
서울혜화
서울방배
서울용산
ETC
서울양천
서울도봉
서울성북
서울서부
서울송파
서울강남
서울강동
서울수서
서울강북
서울혜화
서울중랑
서울서대문
서울강서
서울마포
서울광진
서울동작
서울노원
서울중부
서울동대문
서울관악
서울영등포
서울청
서울서초
서울구로
서울금천
서울성동
서울은평
서울종암
서울방배
서울용산
서울종로
ETC
서울동작
서울강남
서울도봉
서울영등포
서울서부
서울강동
서울서초
서울광진
서울종암
서울강북
서울마포
서울수서
서울노원
서울서대문
서울동대문
서울금천
서울송파
서울청
서울강서
서울중랑
서울관악
서울성동
서울중부
서울혜화
서울방배
서울성북
서울남대문
서울종로
서울양천
서울용산
서울구로
서울은평
ETC
서울방배
서울광진
서울도봉
서울송파
서울강남
서울서초
서울종로
서울종암
서울서부
서울동작
서울강동
서울금천
서울성북
서울강서
서울은평
서울관악
서울강북
서울중부
서울동대문
서울마포
서울수서
서울노원
서울성동
서울구로
서울서대문
서울중랑
서울혜화
서울용산
서울영등포
서울양천
ETC
서울동대문
서울강서
서울강남
서울중부
서울강동
서울노원
서울은평
서울강북
서울동작
서울마포
서울서대문
서울수서
서울도봉
서울방배
서울영등포
서울관악
서울금천
서울송파
서울종로
서울성동
서울광진
서울서초
서울서부
서울중랑
서울성북
서울혜화
서울양천
서울남대문
서울용산
서울구로
서울종암
ETC
서울서부
서울수서
서울중랑
서울서대문
서울광진
서울영등포
서울서초
서울용산
서울송파
서울금천
서울강남
서울도봉
서울은평
서울양천
서울강동
서울동대문
서울성동
서울강북
서울동작
서울마포
서울강서
서울관악
서울종암
서울방배
서울혜화
서울중부
서울노원
서울구로
서울종로
서울청
서울성북
서울남대문
ETC
서울강북
서울동대문
서울금천
서울도봉
서울서부
서울영등포
서울광진
서울노원
서울수서
서울방배
서울관악
서울중부
서울강남
서울성동
서울강동
서울동작
서울마포
서울송파
서울서초
서울구로
서울은평
서울서대문
서울강서
서울중랑
서울용산
서울종암
서울양천
서울혜화
서울성북
서울종로
서울남대문
ETC
서울서부
서울수서
서울강북
서울구로
서울도봉
서울광진
서울금천
서울동작
서울강동
서울송파
서울서초
서울강남
서울동대문
서울노원
서울혜화
서울중랑
서울성동
서울영등포
서울마포
서울서대문
서울종암
서울강서
서울중부
서울방배
서울관악
서울은평
서울종로
서울용산
서울남대문
서울양천
서울성북
ETC
서울도봉
서울방배
서울중부
서울성동
서울서대문
서울동작
서울수서
서울강북
서울금천
서울강서
서울서부
서울노원
서울강남
서울광진
서울중랑
서울강동
서울구로
서울송파
서울동대문
서울종로
서울관악
서울서초
서울성북
서울종암
서울영등포
서울양천
서울혜화
서울은평
서울용산
서울남대문
서울청
서울마포
ETC
서울서부
서울종로
서울동작
서울광진
서울강서
서울강남
서울수서
서울성북
서울강북
서울송파
서울방배
서울영등포
서울서대문
서울중부
서울종암
서울노원
서울도봉
서울중랑
서울금천
서울서초
서울강동
서울관악
서울성동
서울남대문
서울혜화
서울동대문
서울은평
서울구로
서울양천
서울마포
서울용산
ETC
서울광진
서울수서
서울송파
서울서초
서울도봉
서울동작
서울노원
서울서부
서울성동
서울강남
서울동대문
서울종암
서울영등포
서울서대문
서울금천
서울강북
서울강서
서울중랑
서울강동
서울혜화
서울양천
서울성북
서울관악
서울구로
서울중부
서울은평
서울방배
서울남대문
서울마포
서울종로
서울용산
ETC

In [15]:
# 1대1대응 딕셔너리 만들기기
police_to_district = {
    '서울광진': '광진구',
    '서울수서': '강남구',
    '서울송파': '송파구',
    '서울서초': '서초구',
    '서울도봉': '도봉구',
    '서울동작': '동작구',
    '서울노원': '노원구',
    '서울서부': '은평구',
    '서울성동': '성동구',
    '서울강남': '강남구',
    '서울동대문': '동대문구',
    '서울종암': '성북구',
    '서울영등포': '영등포구',
    '서울서대문': '서대문구',
    '서울금천': '금천구',
    '서울강북': '강북구',
    '서울강서': '강서구',
    '서울중랑': '중랑구',
    '서울강동': '강동구',
    '서울혜화': '종로구',
    '서울양천': '양천구',
    '서울성북': '성북구',
    '서울관악': '관악구',
    '서울구로': '구로구',
    '서울중부': '중구',
    '서울은평': '은평구',
    '서울방배': '서초구',
    '서울남대문': '중구',
    '서울마포': '마포구',
    '서울종로': '종로구',
    '서울용산': '용산구',
    'ETC': '기타'
}
fly_df['자치구'] = fly_df['경찰서명'].map(police_to_district)

In [16]:
fly_df.head()

,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,접수긴급유형민원,...,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23,자치구
0,서울강동,24,9,10,5,0,0,2,22,0,...,0,1,1,2,0,3,4,3,3,강동구
1,서울송파,45,36,6,3,0,0,5,40,0,...,1,0,3,4,2,5,4,7,6,송파구
2,서울서초,23,12,3,8,0,0,1,22,0,...,0,0,0,2,4,4,4,2,5,서초구
3,서울강북,52,18,18,16,0,0,6,45,1,...,3,3,0,2,4,4,3,5,4,강북구
4,서울광진,35,15,9,11,0,0,2,32,1,...,0,0,3,3,5,2,2,4,4,광진구

In [17]:
fly_grouped_df = fly_df.groupby('자치구', as_index=False).sum()

In [18]:
fly_grouped_df.head()

,자치구,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
0,강남구,서울강남서울수서서울강남서울수서서울강남서울수서서울강남서울수서서울강남서울수서서울강남서울...,1194,586,254,354,0,0,76,1085,...,11,32,103,70,58,89,84,139,229,149
1,강동구,서울강동서울강동서울강동서울강동서울강동서울강동서울강동서울강동서울강동서울강동서울강동서울강동,1072,570,210,292,0,1,60,982,...,35,55,98,86,92,98,128,101,128,82
2,강북구,서울강북서울강북서울강북서울강북서울강북서울강북서울강북서울강북서울강북서울강북서울강북서울강북,760,365,168,227,0,2,64,671,...,12,32,64,51,57,50,84,76,75,59
3,강서구,서울강서서울강서서울강서서울강서서울강서서울강서서울강서서울강서서울강서서울강서서울강서서울강서,1225,612,273,340,0,0,81,1117,...,30,52,106,99,68,93,99,151,171,103
4,관악구,서울관악서울관악서울관악서울관악서울관악서울관악서울관악서울관악서울관악서울관악서울관악서울관악,606,314,149,143,0,2,64,521,...,9,24,54,40,24,37,57,68,79,53

In [19]:
# 이제 경찰서명은 필요없으니 버린다
fly_grouped_df.drop('경찰서명', axis=1, inplace=True)

In [20]:
# 자치구를 인덱스로
fly_grouped_df.set_index('자치구', inplace=True)

In [21]:
fly_grouped_df.head()

,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,접수긴급유형민원,접수긴급유형기타,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
자치구,,,,,,,,,,,,,,,,,,,,,
강남구,1194,586,254,354,0,0,76,1085,27,6,...,11,32,103,70,58,89,84,139,229,149
강동구,1072,570,210,292,0,1,60,982,23,6,...,35,55,98,86,92,98,128,101,128,82
강북구,760,365,168,227,0,2,64,671,20,3,...,12,32,64,51,57,50,84,76,75,59
강서구,1225,612,273,340,0,0,81,1117,17,10,...,30,52,106,99,68,93,99,151,171,103
관악구,606,314,149,143,0,2,64,521,19,0,...,9,24,54,40,24,37,57,68,79,53

In [22]:
(fly_df['자치구'].unique())

array(['강동구', '송파구', '서초구', '강북구', '광진구', '중랑구', '성북구', '영등포구', '은평구',
       '동대문구', '금천구', '중구', '마포구', '강남구', '강서구', '노원구', '성동구', '도봉구', nan,
       '종로구', '관악구', '용산구', '서대문구', '양천구', '동작구', '구로구', '기타'],
      dtype=object)

nan 값은 서울청, 기타는 경찰서 이름이 적혀있지 않은 ETC 데이터이다.

In [23]:
fly_grouped_df.to_csv('data/processed/서울시_청소년비행(구별매칭완료).csv', encoding='utf-8-sig', index=True)

In [27]:
fly_grouped_df

,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,접수긴급유형민원,접수긴급유형기타,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
자치구,,,,,,,,,,,,,,,,,,,,,
강남구,1194,586,254,354,0,0,76,1085,27,6,...,11,32,103,70,58,89,84,139,229,149
강동구,1072,570,210,292,0,1,60,982,23,6,...,35,55,98,86,92,98,128,101,128,82
강북구,760,365,168,227,0,2,64,671,20,3,...,12,32,64,51,57,50,84,76,75,59
강서구,1225,612,273,340,0,0,81,1117,17,10,...,30,52,106,99,68,93,99,151,171,103
관악구,606,314,149,143,0,2,64,521,19,0,...,9,24,54,40,24,37,57,68,79,53
광진구,837,441,175,221,0,0,49,773,10,5,...,22,39,62,73,66,62,71,83,128,71
구로구,729,403,163,163,0,0,44,662,16,7,...,12,22,65,67,63,53,70,73,84,52
금천구,459,238,135,86,0,0,44,408,7,0,...,7,12,23,23,31,29,36,37,50,50
기타,8357,4722,1810,1825,0,4,355,7349,293,356,...,163,299,607,692,628,651,786,922,1008,755
노원구,1417,806,263,348,0,3,87,1291,33,3,...,20,85,134,101,106,110,113,141,216,119
도봉구,866,472,185,209,0,1,59,785,16,5,...,12,29,47,47,53,76,68,127,107,97
동대문구,342,191,62,89,0,0,23,312,5,2,...,5,19,25,15,19,18,32,30,45,34
동작구,694,334,139,221,0,1,65,615,13,0,...,14,26,46,57,69,72,75,77,88,53
마포구,1158,560,214,384,0,0,65,1066,18,9,...,22,45,83,107,120,128,132,144,133,63
서대문구,456,239,104,113,0,0,30,415,8,3,...,11,13,39,30,31,33,33,46,71,45
서초구,626,329,113,184,0,1,40,561,22,2,...,3,23,44,23,19,43,50,86,121,83
성동구,345,189,74,82,0,0,25,312,6,2,...,3,13,33,24,26,16,35,38,49,31
성북구,1126,532,289,305,0,2,73,1025,19,7,...,12,53,101,103,71,81,137,161,153,76
송파구,1072,538,240,294,0,0,75,977,13,7,...,24,53,68,66,66,59,93,121,158,122
양천구,1023,609,150,264,0,0,62,941,16,4,...,17,43,91,58,61,51,89,116,195,113
영등포구,713,349,170,194,0,2,71,625,10,5,...,6,27,29,55,73,64,67,72,97,56
용산구,99,52,18,29,0,0,10,88,1,0,...,1,8,5,6,4,5,11,11,14,4
은평구,1634,747,307,580,0,0,112,1502,15,5,...,35,58,106,104,109,142,149,208,227,141
종로구,135,82,26,27,0,0,7,117,10,1,...,0,11,11,5,11,10,12,25,14,8
중구,179,113,32,34,0,0,12,163,4,0,...,11,24,32,11,11,9,7,12,12,6
중랑구,705,370,174,161,0,0,43,643,16,3,...,6,22,45,41,45,60,59,88,88,72